### ISSUE TITLE
When registering a user, there needs to be a 60-second countdown on the interface for sending the email activation code 

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBWallet-iOS#1]
When registering a user, there needs to be a 60-second countdown on the interface for sending the email activation code, and you cannot click send again within 60 seconds.

**Comment by neocarmack** [comment]
It should be a bug, if let user send activation code over and over again.

**Comment by yizdream** [comment]
regist sucessful but login fail.  这个提示太快了，怕影响吸引快速注册用户的体验。

**Comment by neocarmack** [comment]
![image](https://github.com/omnilaboratory/OBWallet-iOS/assets/15964933/e4eb3241-51c9-45d3-a9ac-4797e087231c)



like this

**Comment by neocarmack** [comment]
fixed
