### ISSUE TITLE
点击开卡会出现两次扣款

### ISSUE THREAD

**Issue by myan1991** [omnilaboratory/OBWallet-iOS#11]

**Comment by wxf4150** [comment]
我查了下； 是两次开卡记录, 两个开卡记录在同一秒内；应该是app开卡按钮,同一秒内点了两次.

陈立那边也是限制了一个用户只能开一张卡.
我们server端也会检查用户已有卡的数量,不能超过1.

但是同一秒内点了两次. 在后端的两个请求检查,用户还是没有卡状态. 所以两个请求全开卡了.

前端应该限制下.  点下开卡按钮后, 显示loading并禁用了按钮. 如果请求返回了错误提示,再启用按钮.

后端应该也可以再加些限制. 两次连点,第二次时,提示错误.  但是前端不改的话, 虽然两次连点,第一个成功了, 但app会显示第二次错误提示,用户会误以为,自己开卡请求失败了,其实他第一个开卡请求是成功的.

**Comment by wxf4150** [comment]
服务端已经加了并发正开卡请求检查 . 第二次及以后,会提示错误信息.

**Comment by iamgamelover** [comment]
前端也已经修复，加了Loading效果。
