### ISSUE TITLE
在transak购买usdt出现绿色页面

### ISSUE THREAD

**Issue by myan1991** [omnilaboratory/OBWallet-iOS#12]
![Uploading 微信图片_20231208185402.jpg…]()

**Comment by myan1991** [comment]
![微信图片_20231208185402](https://github.com/omnilaboratory/OBWallet-iOS/assets/153280662/65ca46c1-fe80-44f3-94ac-9708a7295291)
![微信图片_20231208185414](https://github.com/omnilaboratory/OBWallet-iOS/assets/153280662/d24f418d-dfa8-4176-9019-5a7bd9d07624)
![微信图片_20231208185419](https://github.com/omnilaboratory/OBWallet-iOS/assets/153280662/9fb3ea50-810e-491a-a01c-3a57fe20e1f8)

**Comment by iamgamelover** [comment]
绿色页面是Transak的加载Loading页面，页面中间应该是显示一个Loading动画，不知道为什么你的截图中没有看到，有可能是网络问题。这不是Bug。
