### ISSUE TITLE
Fill in correct numbers, telling user how much the fee is when swapping

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBWallet-iOS#13]
![image](https://github.com/omnilaboratory/OBWallet-iOS/assets/15964933/e580cd5e-bee1-49dd-8df4-ae1a218911e2)

for example：

1 USD = 0.97 USDT
Slippage 0.5%
Fee 3%
Gas Fee 5 USD

**Comment by iamgamelover** [comment]
已完成
