### ISSUE TITLE
兑换USDT到USD，钱包没有eth做gas fee的时候，点击swap没有反应

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBWallet-iOS#14]
![8277d4fd1c7196306a23c11e536a5e4](https://github.com/omnilaboratory/OBWallet-iOS/assets/15964933/8c907f5c-335c-4c77-9935-b3bcb1f337b1)

点击confirm之后，停留在这个界面。应该提示用户没有足够的eth作为gas fee，提示用户充eth。

关闭页面后，swap没有成功，account余额和crypto余额没有变化。

**Comment by iamgamelover** [comment]
已经添加了提示内容。
