### ISSUE TITLE
提现到虚拟卡(充值)没有提示手续费和实际到卡的金额

### ISSUE THREAD

**Issue by yizdream** [omnilaboratory/OBWallet-iOS#18]
![a028249c4bfbd579c4786daf389bf2f](https://github.com/omnilaboratory/OBWallet-iOS/assets/120292779/06356e8a-8d5b-4b77-9377-c7aefdfe4679)

**Comment by wxf4150** [comment]
相应的手续费配制项及获取配制项的接口都有. 但前端计算会比较麻烦啊
比如 提现10$
如果不是渠道用户,所得额计算: 10- 10* 1%=9.9   其中  1%是平台利润
如果是渠道用用户 ,所得额计算   (10 -0.001) - (10 -0.001)* (1-1.5% -1%) = 9.749=9.74  其中0.001是佣金发放时的gas费； 1.5%是代理商佣金;  1%是平台利润 

这个计算逻辑,及计算结果9.74 , @yizdream 麻烦看下,确认下.

我把这个计算逻辑写个接口给前端用.

**Comment by yizdream** [comment]
@wxf4150 算法没问题。

**Comment by wxf4150** [comment]
9.749=9.74     那个 9.74 有没有问题?    @yizdream

在usd usdt 都是保留两位小数, 再后面的小数抺0.

**Comment by wxf4150** [comment]
添加新接口  card.proto GetWithdrawResAmt 
根据输入的提现金额,返回.

  //去除手续费后的应得金额
  double amt = 2;
  //手续费
  double fee=1;
  
  比如输入10  返回  
 "amt": 9.79,
    "fee": 0.21

**Comment by yizdream** [comment]
这个对了，可以关闭了
