### ISSUE TITLE
代理商佣金算后的手续费不准确

### ISSUE THREAD

**Issue by yizdream** [omnilaboratory/OBWallet-iOS#19]
我的代理佣金应该是>=2.5%（佣金1.5%+平台利润1%+付给代理的Polygon费用0.001）

我的用户充值10元只获得9.9元，说明是1%。

**Comment by wxf4150** [comment]
提issue时.带上尽可能多的信息,  用户名, 什么时间, 什么操作.

我排查了下:
当用户注册时,他使用的邀请码是代理商的码时, 在注册当时会把这个用户"标记为"渠道用户.  
你这个用户在昨天中午注册的, 在他注册时,他使用的邀请码还不是代理商的,所以没有被"标记为"渠道用户, 交易不会产生佣金,只扣平台利润1%, 所以9.9是对的.

昨晚,才把你的指定的用户标记为代理商, 从昨晚开始, 使用你指定的代理商用户的邀请码,注册后才会是渠道用户.

目前我已经手动把你的erbadao1@gmail.com 这个用户标记为渠道用户,你再试下.

**Comment by yizdream** [comment]
这里有问题。做一个系统默认代理商，如果没有代理商时，默认代理商佣金也是平台的利润。不然这块浪费了。

**Comment by iamgamelover** [comment]
已解决
