### ISSUE TITLE
KYC Addrees need to modify

### ISSUE THREAD

**Issue by yizdream** [omnilaboratory/OBWallet-iOS#2]
after you inputed wrong addrees for kyc,  then  you deposit by credit card, show the error "billing address error"
![105bde6dc1695a4cc6998a4a730917b](https://github.com/omnilaboratory/OBWallet-iOS/assets/120292779/d5f0f2b6-b7f8-489a-976b-ee0c36653bf2)

**Comment by wxf4150** [comment]
it's payemt-api err  https://docs.flyzeroc.xyz/payment-zh.html#pomelopay

the api is ok now
