### ISSUE TITLE
代理商的客户开卡和充值，没有及时获得U

### ISSUE THREAD

**Issue by yizdream** [omnilaboratory/OBWallet-iOS#20]
每次消费每次及时结算给代理商，佣金以U的方式打给代理商的U账户。

**Comment by wxf4150** [comment]
每次的佣金是的及时把u发给代理商的. 这个可以操作完成后在  polygonscan 上,及时查看 . 
https://mumbai.polygonscan.com/address/0xbe188d6641e8b680743a4815dfa0f6208038960f  注:这个链接里最后一个段,要换成你的地址 .


代理商的app里显示的"不是"佣金明细 . 是按日期或用户"统计"数据.  
明细是及时新的,但统计是"1分钟"统计更新一次. 
没有必要为了实时一行明细,立即更新所有统计信息. 统计几乎在其它应用的所有场景都是延迟更新的.
