### ISSUE TITLE
开卡的金额提示应该是15？

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBWallet-iOS#22]
![image](https://github.com/omnilaboratory/OBWallet-iOS/assets/15964933/9bb7a800-d5f4-4b48-be7d-24b280a673fa)

**Comment by yizdream** [comment]
这是浮动的，前端找小飞要接口

**Comment by iamgamelover** [comment]
上面截图是旧的版本，新版本是正常的。
