### ISSUE TITLE
虚拟卡到个人账户的逻辑，走虚拟卡接口。另外现在测试环境只充钱到余额增加，卡余额未减少。

### ISSUE THREAD

**Issue by yizdream** [omnilaboratory/OBWallet-iOS#3]
![5770dbedd9b843cfba9321c497782c2](https://github.com/omnilaboratory/OBWallet-iOS/assets/120292779/08196dd7-49ca-4c10-82fa-dfa7da0cd7d1)

虚拟卡到个人账户的逻辑，走虚拟卡接口。另外现在测试环境只充钱到余额增加，卡余额未减少。

**Comment by iamgamelover** [comment]
Fixed
