### ISSUE TITLE
由于有两个,1个是Account，1个是Card, 那么Deposit和WithDraw有点乱。这个可以讨论下。

### ISSUE THREAD

**Issue by yizdream** [omnilaboratory/OBWallet-iOS#5]
![df6a3015b871fa01c8f4b4785f666a7](https://github.com/omnilaboratory/OBWallet-iOS/assets/120292779/e630a2b2-1f70-4454-a2de-18294589805b)
比如上图，卡的提现。卡取出放哪里去，我觉得是不是，
多一个  To Account

**Comment by wxf4150** [comment]
应该是吧。 WithDraw to account .

**Comment by iamgamelover** [comment]
各个弹窗的标题都改为 to Account 或 to Card 了。
